package com.myapp.timer;

import com.myapp.client.Client;
import com.myapp.crawer.impl.ProxyIpCrawerImpl;

/**
 * Created by gaorui on 16/12/26.
 */
public class Timer {
    public static void main(String[] args) {
        // TODO todo.generated by zoer
        ProxyIpCrawerImpl proxyIpCrawer = new ProxyIpCrawerImpl("109.74.75.34");
        java.util.Timer timer = new java.util.Timer();
        timer.schedule(new Client(proxyIpCrawer), 1000, 1000*60);
    }
}
