package com.myapp.timer;

import com.myapp.client.Client;
import com.myapp.crawer.impl.ProxyIpCrawerImpl;
import com.myapp.main.main;

/**
 * Created by gaorui on 16/12/26.
 */
public class Timer {
    public static void main(String[] args) {
        // TODO todo.generated by zoer
        ProxyIpCrawerImpl proxyIpCrawer = new ProxyIpCrawerImpl();
        java.util.Timer timer = new java.util.Timer();
        timer.schedule(new Client(proxyIpCrawer),0,1000 * 60 * 10);
        timer.schedule(new main(), 1000 * 10 ,1000 * 60 * 5 );

    }
}
